services:
  postgres:
    image: postgres:17-alpine
    container_name: urlshortener-db
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - urlshortener-network

  redis:
    image: redis:7-alpine
    container_name: urlshortener-cache
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - urlshortener-network

  # Опционально: Redis Commander для визуального управления Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: urlshortener-redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - urlshortener-network

volumes:
  postgres_data:
  redis_data:

networks:
  urlshortener-network:
    driver: bridge