server:
  host: "localhost"
  port: "8080"

database:
  host: "localhost"
  port: "5432"
  user: "urlshortener"
  password: "password"
  dbname: "urlshortener"

app:
  base_url: "http://localhost:8080"
  short_code_length: 6
  max_retries: 5